samuong/alpaca

contextid.go
contextid_test.go
main.go
pacwrapper.go
pacwrapper_test.go
proxy.go
proxy_test.go
proxyfinder.go
proxyfinder_test.go
requestlogger.go
requestlogger_test.go

Serve a PAC file on `/alpaca.pac` that only returns `DIRECT` or `PROXY localhost:<listen-port>` (usually `3128`). If the PAC file that alpaca is using would return `DIRECT` for a URL, the wrapped PAC also returns `DIRECT`. For everything else, it returns a proxy directive to send traffic to alpaca. If alpaca does not have a PAC file (wrong network, etc), then the PAC function only returns `DIRECT`.
This allows the system (Mac OSX, Gnome, etc) to use alpaca as the proxy, and to configure alpaca with the network proxy URL. When the system evaluates a URL with the wrapped PAC file and gets a DIRECT response, it will not proxy through alpaca and go direct instead. This helps with the odd application that doesn't seem to handle going through a proxy at all. It also means that when you're off …

Serve /alpaca.pac to send non-DIRECT requests to alpaca

---

proxy.go
proxy_test.go

Avoid sending Content-Length on successful CONNECT response

---

proxyfinder.go
proxyfinder_test.go

`ProxyFinder.checkForUpdates()` should only be called if `pf.fetcher` is
not nil. It does this on the HTTP serving path, but not on the initial
call. Move the call to `checkForUpdates()` inside the branch that
creates the pacfetcher.
Fixes this bug:
sam@sam-desktop:~/alpaca$ go build && ./alpaca
2019/09/19 19:13:28 proxyfinder.go:24: No PAC URL specified or detected; all requests will be made directly
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x855e7e]
goroutine 1 [running]:
main.(*pacFetcher).download(0x0, 0x0, 0x0, 0x0)
/home/sam/alpaca/pacfetcher.go:51 +0x4e
main.(*ProxyFinder).checkForUpdates(0xc00000e0c0)
/home/sam/alpaca/proxyfinder.go:50 +0x76
main.NewProxyFinder(0x0, 0x0, 0xc000170480, 0x0) …

Don't call checkForUpdates without a fetcher

---

proxy.go
proxy_test.go

Construct and write an http.Response rather than a hardcoded string

---

main.go
nomad_darwin.go

This allows Alpaca to distinguish between having no credentials, and having a blank domain/username/password.

Return a pointer to an authenticator

---

pacfetcher.go
pacfetcher_test.go

I can't think of a better way to fix issue #8. This should work around it in most, if not all, cases.

Retry PAC downloads after 2 seconds in case of failure

---

pacrunner_test.go

The TestWeekdayRange test was failing when run in the UTC or
America/Pacific timezone (and probably others). This is because when
parsing a timezone name, that name needs to be defined in for the
current location - from the time.Parse docs:
When parsing a time with a zone abbreviation like MST, if the zone
abbreviation has a defined offset in the current location, then that
offset is used.
Presumably the name "AEST" used in the reference Sunday time is not
defined in other locations.
So use the RFC1123Z format and be explicit about the +1000 offset,
rather than relying on the zone abbreviation.
Fixes: #46

tests: Fix sunday time to properly include timezone

---

README.md

Also, I've moved the "Download Binary" method down one section, because I think
that Homebrew and Go both provide a better (automated) way to keep the binary
up-to-date.
Also, I've added `http://` to `http_proxy` and `https_proxy`. This seems to be
needed by `yarn`.
Fixes #55

Add instructions to install via Homebrew

---

cancelable/closer.go
cancelable/example_closer_test.go
proxy.go

This PR has two separate commits, and will be merged using a fast-forward merge.

Add godocs for the cancelable package, and remove an unnecessary call to server.Close()

---

contextid.go
contextid_test.go
proxy.go
proxyfinder.go
proxyfinder_test.go
requestlogger.go
requestlogger_test.go

Also, use sync/atomic's AddUint64() to generate IDs, which is simpler
and avoids tying up a goroutine.
Fixes #17

Remove bare string used as context key

---

authenticator.go
proxy.go
transport.go
transport_test.go

The purpose of this change is to reduce code duplication in
`authenticator.go`. Previously, we needed to have two separate
implementations of the NTLM handshake: one for CONNECT requests (which
are written directly to a `net.Conn`) and another for all other requests
(which are sent via an `http.Transport`). Now that we only need one
(written against any `http.RoundTripper`), it will be simpler to
implement additional authentication protocols in the future, such as
Kerberos.

Introduce a `transport` type to write HTTP requests to a `net.Conn`

---

.github/workflows/ci.yml
.github/workflows/release.yml
pacfetcher.go
pacfinder_darwin.go
pacfinder_darwin_test.go
pacfinder_unix.go
pacfinder_unix_test.go
pacfinder_windows.go

I'm not sure why we didn't have it set up to run Windows builds and tests on Windows itself, but this was hiding a number of bugs on Windows.

Run lint/release jobs on Ubuntu, and Windows build/tests on Windows

---

.github/workflows/release.yml

EDIT: I've added two more commits.
Commits: 
1. bugfix: windows binary to include .exe extension that would otherwise make it difficult for users to execute.
2. refactor: release asset naming convention to "alpaca_[version]_[platform]?[.extentsion]"
3. refactor: the build release asset job to use the previous job outputs consistently.

windows binaries .exe extension to build refinements

---

pacrunner.go
pacrunner_test.go
proxyfinder.go

Also change FindProxyForURL() to pass by value rather than by reference. This
function modifies the URL, so make sure to do that on a copy rather than on the
original.
Fixes #58

Pass complete URLs to PAC script, assuming https if scheme is empty

---

main.go
proxy.go
proxy_test.go
proxyfinder.go

This lets us run the proxy resolution code only once, even if we have to
perform multiple requests (e.g. for authentication).

Run proxy finder function and add result to request context

---

main.go
pacfetcher.go

This allows Alpaca to detect changes in the system's PAC URL. Some VPN
clients change the PAC URL to a locally-hosted file upon connection, so
this needs to be checked whenever a network change is detected.

Try to determine PAC URL before downloading, rather than on startup

---

authenticator.go
proxy.go

When a proxy server responses with 407 Proxy Authentication Required, Alpaca silently retries the request with authentication. This PR adds logging so that we know when Alpaca has gone down the code path to authenticate to the proxy. This makes it easier to see what's going on in cases such as issue #44.

Log 407 responses from proxy

---

proxy.go
proxy_test.go
transport.go

This pull request re-lands #75, which was accidentally merged into the wrong branch (fixed-proxy-during-auth instead of master).
This PR is currently compared against reland-pr-74, but should be rebased and merged into master once reland-pr-74 lands.

Use net.OpError instead of our own dialError type

---

AUTHORS
main.go

Server currently listens on `localhost:${port}` which is fine for most scenarios
This adds the ability to optionally listen on `:${port}` instead (all local IPs)
It's unknown whether this has far reaching implications - very much included just as a jump off point for samuong/alpaca#95 if desired
Potentially addresses samuong/alpaca#95
**NB: previous commits removed since it was a tiny change and clashed with recent merges**

Add flag to optionally listen on all interfaces

---

main_test.go

This was broken in #96 but missed since it is disabled by default

Fix broken test

---

main_test.go
proxy_test.go

Alpaca doesn't support HTTP/2, but clients and servers that support it can
still communicate using HTTP/2, over a CONNECT tunnel established over HTTP/1.
Fixes #6

Add a test for HTTP/2

---

pacfinder_darwin.go
pacfinder_darwin_test.go

On some machines, for some network services, networksetup returns a blank URL instead of `(null)`. This needs to be ignored by Alpaca, otherwise we'll fail to detect PAC URLs that are set in other network services.

Handle empty URLs in output from networksetup

---

main.go
pacfetcher.go
pacfetcher_test.go
pacfinder_darwin.go
pacfinder_darwin_test.go
pacfinder_unix.go
pacfinder_unix_test.go
pacfinder_windows.go
proxyfinder_test.go

This PR suggests a way of using cgo to performantly (< 100uS) pull the auto proxy configuration from the darwin system to ensure always having the current setting.

Always check for new PAC files on darwin.

---

pacfetcher.go
pacfetcher_test.go

This behaviour worked well on some corporate networks, but breaks on others. From now on, users who use a custom PAC file with a file:// URL will need to do this check themselves, before returning a PROXY directive.
Fixes #106

Remove dodgy connection check

---

proxy.go

This introduces a few changes from the previous version:
1. If we build an http.Response and call its Write() function, it will
write the response line-by-line. This seems to be the cause of some
flakiness with clients that start tunnel mode after the status line,
rather than after the response header, as per RFC9110 9.3.6.
2. We only support HTTP 1.0 and 1.1. We no longer just blindly copy over
the HTTP version from the client request.
3. The status code is still 200 but the status message has changed from
"OK" to "Connection Established", in line with what other proxies are
doing (I tested Squid, Martian and Zscaler). Clients ignore this
anyway, going with the status code, so this shouldn't matter.
4. We no longer send a 'Connection: close' header with the response.
This is redundant in …

Write CONNECT response in a single call to Conn.Write()

---

authenticator.go
proxy.go

Close response body before moving on to next request/response

---

pacrunner.go
pacrunner_test.go

Reimplement myIpAddress() to align with Chrome's algorithm

---

AUTHORS
main.go

Why not set dual stack IPv4 and IPv6 by default? 
In that cause both protocols can coexist and the user can choose the one that it wants the most. The current implementation works as a tunnel as well. Example:
My Package -> Proxy: https://[::1]:3128 -> Network: some IPv4

Fix: dual stack network not working
